### ISSUE TITLE
region references

### ISSUE THREAD

**Issue by magland** [NeurodataWithoutBorders/lindi#29]
@oruebel @rly 

Do you have a dandi example that uses region references? And a way to check that they are being loaded properly in pynwb?

Thx.

**Comment by rly** [comment]
Region references are not fully supported in the NWB software, so we can ignore those.

**Comment by oruebel** [comment]
Region references in the HDF5 sense (I.e. referencing an arbitrary subblock of a dataset) are currently not being used in NWB. When we need to reference subsets, we define our own types. In particular DynamucTableRegion is a type that we use where the dataset stores the indices (rows in a table) we want to select and an attribute with an object reference defines the target (here a DynamicTable, so the selection applies to the whole table not just a dataset). Another example is TimeSeriesReference to select a range in time from a TimeSeries. NWB does this in part because the selections we need apply to higher-level data types (not just individual datasets) and because region references are not easy to introspect (eg. to get the indices rather than the data) and it's easy to use them in an inefficient way. Long story short, for the purposes of NWB it's ok to leave RegionReferences out of scope

**Comment by magland** [comment]
Got it, thanks.
